### ISSUE TITLE
looplessness.py

### ISSUE THREAD

**Issue by Arstory-MK** [barahona-research-group/hcga#101]
Exception: Feature trophic_levels_mean of type <class 'sympy.core.number.Rational'> with no stat does not return expected type(<class 'int'>, <class 'float'>, <class 'numpy.int32'>, <class 'numpy.int64'>, <class 'numpy.float32'>, <class 'numpy.float64'>): 87084457773804983/8951285981180400

Seemed to have fixed this error by deleting .\hcga\features\looplessness.py.

**Comment by arnaudon** [comment]
@peach-lucien , could you take a quick look?

**Comment by peach-lucien** [comment]
@arnaudon  yep - I have booked some time for sunday to work out what is going wrong here!

**Comment by peach-lucien** [comment]
I think I have fixed this now.
