### ISSUE TITLE
'Too many open files' error

### ISSUE THREAD

**Issue by Arstory-MK** [barahona-research-group/hcga#102]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/77487493/147502648-050867d7-365c-4bb7-a15d-0017a3c45b43.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77487493/147502650-86fa20c6-39c9-4faf-849b-f3b8d58c6d8c.png)

**Comment by arnaudon** [comment]
try to run `export OMP_NUM_THREADS=1` before you launch the code, it seems your setup is creating too many parallel things and failed. This export (there are others I forgot the name) prevent numpy and friends to run in parallel).

**Comment by arnaudon** [comment]
Hello! Could you try to run with this branch? https://github.com/barahona-research-group/hcga/pull/103 (`git fetch & git checkout fix_pool`) and let me know if it works better?

**Comment by arnaudon** [comment]
Hold on, it does not yet work!
