### ISSUE TITLE
add fit of features against distributions

### ISSUE THREAD

**Issue by arnaudon** [barahona-research-group/hcga#16]
with some options (basic, medium, advanced)

**Comment by arnaudon** [comment]
@peach-lucien you said this was not helping? do we want to include or not?

**Comment by peach-lucien** [comment]
it can be added but for now its not useful I don't believe. Its somewhat dependent on how one bins the data and that just bloats the feature space for no large benefit.

**Comment by peach-lucien** [comment]
can close this - I still have the issue open for the powerlaw feature which we can add later.
