### ISSUE TITLE
pandas dataframe sorting

### ISSUE THREAD

**Issue by peach-lucien** [barahona-research-group/hcga#41]
We may want to consider sorting the pandas dataframe according to graph label for easier exploration. 

Also you mentioned something about info_ict but not sure what you're referring to?

**Comment by arnaudon** [comment]
make the info_dict compatible with pandas structure/or even include it in the pandas structure

**Comment by arnaudon** [comment]
now the features_info is a dataframe with the same multicolumns as the all_features dataframe. Wee need to update the analaysis/ploting accordingly
