### ISSUE TITLE
save graph labels and labels id

### ISSUE THREAD

**Issue by arnaudon** [barahona-research-group/hcga#61]
if the user gives graph label that is not integer, save it in another variable and assign an label_id to it

**Comment by arnaudon** [comment]
partially done, but we need to propagate that in plotting

**Comment by arnaudon** [comment]
also need to allow for an option for graph regression (@peach-lucien binning the continuous value on the GraphCollection from continuous graph label?)

**Comment by arnaudon** [comment]
@peach-lucien did you solve that?

**Comment by peach-lucien** [comment]
yes it now allows regression task's - there is an example notebook implementing a regression too.
