### ISSUE TITLE
node clique number feature

### ISSUE THREAD

**Issue by peach-lucien** [barahona-research-group/hcga#86]
The acronym name for node_clique_number.py is CN - this is the same as the core number acronym. We should change this to CLN for node clique number.

**Comment by arnaudon** [comment]
I see CoN for core number and CN for node_clique_number, am I right?

**Comment by peach-lucien** [comment]
my mistake... I meant node_clique_number.py and node_connectivity.py 

brain fart

**Comment by arnaudon** [comment]
shortname = "NC" 
shortname = "CN"
